Check for breaking symbolic links (#312)
* Check for breaking symbolic links

* Fixing broken links

* Update script

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -33,6 +33,20 @@ workflows:
     - git-clone:
         title: CLONE SECP256K1.SWIFT
         timeout: 60
+    - script:
+        title: CHECK LINKS
+        timeout: 20
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails; debug log
+            set -ex
+            
+            # This command finds broken symbolic links in a directory and subdirectories.
+            # It uses the find command to follow symbolic links and checks if they are
+            # broken with the test command. If a broken symbolic link is found, the
+            # script fails with a non-zero status code.
+            find . -type d -name .build -prune -o -type l ! -exec test -e {} \; -print | grep -q . && exit 1 || exit 0
     - deploy-to-bitrise-io:
         inputs:
         - pipeline_intermediate_files: "$BITRISE_SOURCE_DIR:BITRISE_SOURCE_DIR"
@@ -42,7 +56,7 @@ workflows:
     steps:
     - script:
         title: BUILD ZKP
-        timeout: 120
+        timeout: 180
         inputs:
         - content: |-
             #!/usr/bin/env bash
@@ -56,7 +70,7 @@ workflows:
     steps:
     - script:
         title: BUILD SECP256K1
-        timeout: 120
+        timeout: 180
         inputs:
         - content: |-
             #!/usr/bin/env bash
